In [17]:
import numpy as np
#import math
#For question 1 solving some linear systems
#We have to make A = [ 1 0 4 ;
#                       5 2 -2
#                       2 9 3  ]
#diagonally dominant by multiplying it on the left by a matrix P. How can we do this?
#After some calculations we found the following strategy (there are many simpler strategies than this :D ):
#We transpose original matrix and then solve A^T (p_i) to obtain the rows of P
A_1 = np.array([[1, 5, 2],
                [0, 2, 9],
                [4,-2,3]])
row_1 = np.linalg.solve(A_1, np.array([5,0,4]))
row_2 = np.linalg.solve(A_1,np.array([5,8,-2]))
row_3 = np.linalg.solve (A_1,np.array([2,9,12]))

P = np.vstack((row_1,row_2,row_3))
#Let's check PA_1 works, it should be as A = A_1.T but with the diagonals increased (5 8 12 specifically).
print(P @ A_1.T)

[[ 5.00000000e+00  2.77555756e-17  4.00000000e+00]
 [ 5.00000000e+00  8.00000000e+00 -2.00000000e+00]
 [ 2.00000000e+00  9.00000000e+00  1.20000000e+01]]


Use vectorized operations to compute the vector 
$$
\left[A[1,1] - \sum_{k\not=1}|A[1,k]|,  A[2,2] - \sum_{k\not=2}|A[2,k]|, 
\dots, A[N,N] - \sum_{k\not=N}|A[N,k]|\right] 
$$  

In [18]:
#Let's test it on this matrix.
A = np.arange(25)
A = np.reshape(A,(5,5))

#first let's stract A diagonal:
A_ii = np.diag(np.diag(A))

#next we will create a new matrix not containing these diagonals to obtain \sum |a_ik| k \neq i
A_ik = np.abs(A) - np.abs(A_ii)
#next time to add the rows of A_ik:
sum_no_diag = A_ik @ np.ones(5,)

#Finally, we take the difference between the diagonal and the absolute sum:

final_vector = np.diag(A) - sum_no_diag
print("the final vector is")
print(final_vector)

the final vector is
[-10. -23. -36. -49. -62.]


(c) Take a random matrix $A \in \mathbb{R}^{11 \times 10}$ and a random vector $b \in \mathbb{R}^{11}$.
``Solve" the overdetermined system $A x = b$ to have $x_h$ 
and compute the error $\|Ax_h - b\|$ of the approximation.
You may use the subroutine scipy.linalg.lstsq.


In [19]:
#Let's generate a random matrix:
A_random = np.random.rand(11,10)
#Let's create a random vector:
b_random = np.random.rand(11,)

#Solving the system using scipy.linalg.lstsq
import scipy
#The syntax of this function is: x, residuals, rank, singular_values = np.linalg.lstsq(A, b, rcond=None)
sol_app = scipy.linalg.lstsq (A_random, b_random)
#What is the rank of our matrix? 
print(f"The rank of this random matrix is {sol_app[2]}")
#if rank(A) = #number of columns, then we know the sol for Ax=b is unique
#iff b belogns in the col(A), so we can check this by checking the rank of 
# the augmented matrix(A |b).

The rank of this random matrix is 10


In [20]:
#Let's check the residual error:
error = np.linalg.norm(A_random @ sol_app[0] - b_random)
print(f'The residual error measured as ||Ax-b||_2 ={error}')

The residual error measured as ||Ax-b||_2 =0.1391770270704072
