In [1]:
# we need it in all codes
import numpy as np 
import math

#Sometimes we will also will require to plot things
import matplotlib.pyplot as plt

# see functions here
# https://numpy.org/doc/stable/reference/generated/numpy.exp.html
# https://numpy.org/doc/stable/reference/routines.array-manipulation.html
#

# basic vector and matrix operations
# general principle: we do not have to write functions for everything
# moreover, built-in vectorized operations are rather fast



In [2]:
#two sample vectors
v = np.array([-2, 0, 3])
w = np.array([4, 2, -1])
#Not the same:
#For lists, * is a repetition operator, and + a concatenation operator.
z = [ -2, 0, 3]
y = [ 4, 2, -1]

print(2*z)
print(z+y)
#For numpy arrays, * is a multiplication operator, and + an addition operator.
print(2*v)
print(v+w)

#Numpy arrays are more efficient than lists, and they support a wide range of operations!
print(v**2)
print(np.sqrt(abs(v)))
#We can even obtain boolean arrays:
print( v>0)
print(w[v>0])

[-2, 0, 3, -2, 0, 3]
[-2, 0, 3, 4, 2, -1]
[-4  0  6]
[2 2 2]
[4 0 9]
[1.41421356 0.         1.73205081]
[False False  True]
[-1]


# CREATING VECTORS

In [3]:
#create them completely manually
v = np.array([-2, 0, 3])
w = np.array([4, 2, -1])
print(v)
#print(w)

[-2  0  3]


In [4]:
# shorthand operations to create them
ones_vect = np.ones(9)

# 7 numbers uniformly between -2 and 4 (including themselves)
v_plus = np.linspace(-2, 4, 7)

# now we can create a vector of 101 numbers uniformly between 0 and 1 (including themselves)
v_new = np.linspace(0,1,101)


print(ones_vect)
print(v_plus)
print(v_new)

[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[-2. -1.  0.  1.  2.  3.  4.]
[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99 1.  ]


In [5]:
# very frequently: just take a random vector (uniformly distributed, between 0 and 1)
w_1 = np.random.rand(5)
print(w_1)
# construct a 2x2 matrix with random numbers uniformly between 0 and 2
w = np.random.rand(2,2)
w = 2*w
print(w)

#What about between -1 and 1?
w_2 = np.random.rand (5)
w_2 = 2*w_2 - 1
print(w_2)
#TIP: we can also use np.random.uniform(-1,1,5) to get the same result
w_3 = np.random.uniform(-1,1,5)
print(w_3)

[0.46967305 0.84091808 0.0402702  0.72145967 0.76501967]
[[1.97797997 0.75313811]
 [0.42868095 1.2166573 ]]
[-0.61309697  0.40461593 -0.84005729 -0.9276769   0.01161717]
[-0.6034282  -0.4310216   0.61278819 -0.83286355 -0.44133295]


# MANIPULATING VECTORS

In [6]:
#one can transpose and ask for the shape
#Hoewever, for 1D arrays, the transpose does not change anything.
vT = np.transpose(v)
print(vT)
print(np.shape(vT))
print(np.shape(v))
#get the last element of vT and check with v:
print(vT[-1])
print(v[-1])

[-2  0  3]
(3,)
(3,)
3
3


In [7]:
# difference of the consecutive numbers
diff_vect = np.diff(v_plus)
# Take the second and the fifth components
# Be careful:  indexing begins with zero   AND  use square brackets
just2and5_vect = v_plus[[2,5]]
print(diff_vect)
print(just2and5_vect)



[1. 1. 1. 1. 1. 1.]
[0. 3.]


In [8]:
#We can also use boolean indexing!!
# elements less than 1.5 change to zero
v_plus[v_plus<1.5] = 0
print(v_plus)
# change element that are larger than 2.1 to 2
v_plus[v_plus>2.1] = 2
print(v_plus)
#If we want to add more conditions, we can use the & operator (and) and the | operator (or)
v_plus[(v_plus<3) & (v_plus>1)] = 0.5
print(v_plus)

[0. 0. 0. 0. 2. 3. 4.]
[0. 0. 0. 0. 2. 2. 2.]
[0.  0.  0.  0.  0.5 0.5 0.5]


In [9]:
# remove the second and the last element
# here index -1 yields the last element
#This creates a new array! it does not modify v_plus.
np.delete(v_plus,[1,-1]) 
# try also to  flip, sort and take the maximum of vector elements
#Tip: delete also takes boolean arrays as input, it will delete elements for which the boolean array is True

array([0. , 0. , 0. , 0.5, 0.5])

In [10]:
# flip the elements of this vector: [1, 2, 4, 8, 0]
#Equivalent (in 1D) to v[::-1] 
np.flip(np.array([1,2,4,8,0]))
#Here the notation is start:stop:step, then [::n] gives every nth element, starting form 0 and all the way to the end.
y = np.array([1,2,3,4,5])
y_1 = y[::2] # every second element
y_2 = y[1:5:2] # every second element, starting from the second
print(y_1)
print(y_2)

[1 3 5]
[2 4]


In [11]:
# take elements of index 0,2,4,...(even indices) from the given random 
# vector of length 30
w = np.random.rand(30)
w_sec = w[::2]
print(w_sec)

[0.66789368 0.08645579 0.68001272 0.28960299 0.44305328 0.51833892
 0.8655917  0.25122559 0.64755061 0.09028203 0.82156315 0.76845251
 0.53111889 0.41311529 0.95194425]


In [12]:
# sort the result of the previous one
np.sort(w_sec)

array([0.08645579, 0.09028203, 0.25122559, 0.28960299, 0.41311529,
       0.44305328, 0.51833892, 0.53111889, 0.64755061, 0.66789368,
       0.68001272, 0.76845251, 0.82156315, 0.8655917 , 0.95194425])

# OPERATION WITH DIFFERENT VECTORS

In [13]:
# In Python, operations are by default, elementwise 
# a number of elementwise operations

v_a   = np.array([-2, 0, 3])
v_b   = np.array([4, 2, -1])
print(v_a)
print(v_b)
print(v_a + v_b)
print(v_a - v_b)
print(v_a * v_b)
print(v_a/v_b)
print(np.exp(v_a))
np.shape(v_a)

[-2  0  3]
[ 4  2 -1]
[2 2 2]
[-6 -2  4]
[-8  0 -3]
[-0.5  0.  -3. ]
[ 0.13533528  1.         20.08553692]


(3,)

In [14]:
# one can concatenate them also
vw = [v, w]
print(vw)
# be careful, this will not be a vector
# for this, one should use, e.g. "hstack"
print(np.hstack((v,w)))
#Similarly, np.concatenate((v,w)) will also work, but it is more general and can be used for higher-dimensional arrays as well.
print(np.concatenate((v,w)))

[array([-2,  0,  3]), array([0.66789368, 0.8294886 , 0.08645579, 0.17230642, 0.68001272,
       0.03781673, 0.28960299, 0.1632614 , 0.44305328, 0.32242604,
       0.51833892, 0.6109048 , 0.8655917 , 0.67797772, 0.25122559,
       0.06925477, 0.64755061, 0.17087808, 0.09028203, 0.07126327,
       0.82156315, 0.80602699, 0.76845251, 0.67948028, 0.53111889,
       0.18681755, 0.41311529, 0.02983037, 0.95194425, 0.81802234])]
[-2.          0.          3.          0.66789368  0.8294886   0.08645579
  0.17230642  0.68001272  0.03781673  0.28960299  0.1632614   0.44305328
  0.32242604  0.51833892  0.6109048   0.8655917   0.67797772  0.25122559
  0.06925477  0.64755061  0.17087808  0.09028203  0.07126327  0.82156315
  0.80602699  0.76845251  0.67948028  0.53111889  0.18681755  0.41311529
  0.02983037  0.95194425  0.81802234]
[-2.          0.          3.          0.66789368  0.8294886   0.08645579
  0.17230642  0.68001272  0.03781673  0.28960299  0.1632614   0.44305328
  0.32242604  0.51833892 

# CREATING MATRICES

In [15]:
# completely manually
 #np.array ( [ [1st row ],  [2nd row ], ..., [nth row] ] )
#the shape will be np.shape(...) = (n, row size)
# row-wise
print("Creating a matrix A using np. array:")
A = np.array([[-2, 1, -3, 2],[4, 1, -2, 0]])
print(A)
print("Checking its shape")
print(np.shape(A))

#Be careful with []!
print("Creating A_1, a 3 dimensional array. This array contains 1 matrix inside of size 2x4")
A_1 = np.array([ [[-2, 1, -3, 2],[4, 1, -2, 0]] ] )
print(A_1)
print("Hence, its shape is:")
print(np.shape(A_1))
#This has become a 3D array, with shape (1,2,4). The first dimension is the number of matrices, the second is the number of rows, and the third is the number of columns.

A_2 = np.array([ [[-2, 1, -3, 2],[4, 1, -2, 0]] , [[1, 1, 1, 1],[1, 1, 1, 1]] ])
print("Creating A_2, a 3 dimensional array with 2 matrices inside, each of side 2x4")
print(A_2)
print("Hence, its shape is:")
print(np.shape(A_2))

Creating a matrix A using np. array:
[[-2  1 -3  2]
 [ 4  1 -2  0]]
Checking its shape
(2, 4)
Creating A_1, a 3 dimensional array. This array contains 1 matrix inside of size 2x4
[[[-2  1 -3  2]
  [ 4  1 -2  0]]]
Hence, its shape is:
(1, 2, 4)
Creating A_2, a 3 dimensional array with 2 matrices inside, each of side 2x4
[[[-2  1 -3  2]
  [ 4  1 -2  0]]

 [[ 1  1  1  1]
  [ 1  1  1  1]]]
Hence, its shape is:
(2, 2, 4)


In [16]:
# one can use simple matrices
A1 = np.ones((4,3))
# do  not forget double brackets
# could be "zeros"
print(A1)
Ad3 = np.eye(4)
# the unit matrix
print(Ad3)
#one can modify an element
Ad3[2,2] = 3
print(Ad3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 1.]]


In [17]:
# Construct a 2 x2 block matrix such that BLOCK[1,1] and BLOCK[2,2]  are 4x4 ones-matrices
# BLOCK[1,2] and BLOCK[2,1] are identity matrices
AA = np.ones((4,4))
BB = np.eye(4)
#first glue together rows: 
BLOCK1_row = np.hstack((AA, BB))
BLOCK2_row = np.hstack((BB, AA))
#then columns
BLOCK_full = np.vstack((BLOCK1_row, BLOCK2_row))

# or just in one step - be careful with brackets
BLOCK = np.vstack((np.hstack((AA, BB)), np.hstack((BB, AA))))
print(BLOCK)

print(np.linalg.norm(BLOCK_full - BLOCK))


[[1. 1. 1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 0. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0. 1. 0.]
 [1. 1. 1. 1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1. 1. 1. 1.]
 [0. 1. 0. 0. 1. 1. 1. 1.]
 [0. 0. 1. 0. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1. 1. 1.]]
0.0


In [18]:
#we can pick a column
B = A[:,-1]
#or just create a matrix using the last two columns
BB = A[:,[1,2]]
print(B)
print(BB)
# you can extract the diagonal
np.diag(Ad3)

[2 0]
[[ 1 -3]
 [ 1 -2]]


array([1., 1., 3., 1.])

In [19]:
np.shape(B)
np.shape(BB)

(2, 2)

# MATRIX and MATRIX-VECTOR OPERATIONS

In [20]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

B = np.array([[-1, 0, 1], [3, 5, 4], [2, 0, 5]])

# be careful: this is again the elementwise operation!!
print("Addition A+B")
print(A + B)
print("Multiplication A*B")
print(A*B)
print("Power A^2")
print(A**2)



Addition A+B
[[ 0  2  4]
 [ 7 10 10]
 [ 9  8 14]]
Multiplication A*B
[[-1  0  3]
 [12 25 24]
 [14  0 45]]
Power A^2
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [21]:
#Proper matrix multiplication is done using the @ operator
print(A @ B)


[[11 10 24]
 [23 25 54]
 [35 40 84]]


In [22]:
# one can construct a block matrix
#using np.block
np.block([[A, A],[B, np.eye(3)]])

array([[ 1.,  2.,  3.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  4.,  5.,  6.],
       [ 7.,  8.,  9.,  7.,  8.,  9.],
       [-1.,  0.,  1.,  1.,  0.,  0.],
       [ 3.,  5.,  4.,  0.,  1.,  0.],
       [ 2.,  0.,  5.,  0.,  0.,  1.]])

In [23]:
# Surprisingly, the @ operator also does Matrix-vector multiplication even if the vector is given as a list!
A @ [1, 1, 1]

array([ 6, 15, 24])

In [24]:
#Recall Python does not care for 1D arrays if they are transposed or not!
A @ np.transpose([1, 1, 1])

array([ 6, 15, 24])

In [25]:

#Let's try to compute the inverse of A:
#A_inv = np.linalg.inv(A) whoops! an error occurs!

In [26]:
#What happpened? Let's check its determinant
print(np.linalg.det(A))

-9.51619735392994e-16


In [27]:
#What if we want to build a diagonal matrix based on a vector?
v = np.array([1,2,3,4,0])
#We can use np.diag!
A_v = np.diag(v)
print("Creating a matrix such that its diagonal is v")
print(A_v)
#We can even choose which diagonal
print("Creating a matrix such that its off-diagonal is v")
B_v = np.diag(v,-1)
print(B_v)

#What if we want to modify the diagonal of an existing matrix:
print("Modifying the diagonal of A_v")
np.fill_diagonal(A_v, [-1,1,-1,1])
print(A_v)

Creating a matrix such that its diagonal is v
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 0]]
Creating a matrix such that its off-diagonal is v
[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 0 0]]
Modifying the diagonal of A_v
[[-1  0  0  0  0]
 [ 0  1  0  0  0]
 [ 0  0 -1  0  0]
 [ 0  0  0  1  0]
 [ 0  0  0  0 -1]]


In [30]:
#What if we want to fill another diagonal? use indexing

A_v [np.arange(1,5) , np.arange(0,4) ] =3

print(A_v)

[[-1  0  0  0  0]
 [ 3  1  0  0  0]
 [ 0  3 -1  0  0]
 [ 0  0  3  1  0]
 [ 0  0  0  3 -1]]
