In [2]:
# we need it in all codes
import numpy as np 
import math

# we also need this one
from numpy.linalg import matrix_power

# see functions here
# https://numpy.org/doc/stable/reference/generated/numpy.exp.html
# https://numpy.org/doc/stable/reference/routines.array-manipulation.html
#

# basic vector and matrix operations
# general principle: we do not have to write functions for everything
# moreover, built-in vectorized operations are rather fast


#  MATRIX REPRESENTATIONS FOR LINEAR MAPPINGS

In [12]:
#create the matrix of the linear map that flips first and and 
#last coordinates in the three-dimensional 
#Euclidean space 
#Recall:  np.array ( [ [1st row ],  [2nd row ], ..., [nth row] ] )

A =np.array( [ [0], [0], [1] ] )
print("A at start, just a column vector")
print(A)
print("shape of A:")
print(np.shape(A))
#np.hstack will add elements to each array horizontally
#to join arrays horizontally, they must have the same number of rows
print("Adding a new column with hstack")
A = np.hstack(( A, [ [0], [1], [0] ] ) )
print(A)
A = np.hstack( ( A,[ [1], [0], [0] ] ) )
print("Adding a new column with hstack")
print(A)
#What is the 200th power of this matrix? 
print("Matrix power:")
print(matrix_power(A,200))

# check this using a random vector
w = np.random.rand(3)
print("checking if this actually flips vector coordinates, this outcome should be (0,0,0):")
print(A@w - np.array([w[2], w[1], w[0]]))





A at start, just a column vector
[[0]
 [0]
 [1]]
shape of A:
(3, 1)
Adding a new column with hstack
[[0 0]
 [0 1]
 [1 0]]
Adding a new column with hstack
[[0 0 1]
 [0 1 0]
 [1 0 0]]
Matrix power:
[[1 0 0]
 [0 1 0]
 [0 0 1]]
checking if this actually flips vector coordinates, this outcome should be (0,0,0):
[0. 0. 0.]


In [ ]:
#create the matrix of the linear map that flips first and and last coordinates in the 60-dimensional 
#Euclidean space
A =np.eye(60)
A[59,0] = 1 
A[0,59] = 1
A[0,0] = 0
A[59,59] = 0
print(A)

[[0. 0. 0. ... 0. 0. 1.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


In [ ]:
#Create the matrix of the linear maps  that multiplies the first 
#corrdinate with two, 
#the second one with three and the third coordinate will be 
#the sum of the first and second coordinates
A =np.array([[2, 0, 0]])
A = np.vstack((A,[[0, 3, 0]]))
A = np.vstack((A,[[1, 1, 0]]))
print(A)
print("what is the inverse of this matrix?")

print(f"Its det= {np.linalg.det(A)}, it has no inverse")
#we can also see it by looking at the number of independent columns

[[2 0 0]
 [0 3 0]
 [1 1 0]]
what is the inverse of this matrix?
Its det= 0.0, it has no inverse


In [ ]:
# Create the matrix corresponding to the rotation with 60 degrees and -90 degrees.
# Compute the 60th power of them
# Can you see this without any computation?
A =np.array([[1/2], [-math.sqrt(3)/2]])
A = np.hstack((A,[[math.sqrt(3)/2], [1/2]]))
print("Matrix corresponding to 60 degree rotation")
print(A)
B = np.array([[0], [-1]])
B = np.hstack((B,[[1], [0]]))
print("Matrix corresponding to -90 degree rotation")
print(B)
print("Matrix corresponding to 60 degree rotation to the nth power")
print(matrix_power(A,60)) 
# Roundoff errors may emerge.
print("Matrix corresponding to -90 degree rotation to the nth power")
print(matrix_power(B,60))
# Take also the inverse of this matrix
# What is the image of the vector [1,2]?
# Which vector is mapped into [4,-2]?


Matrix corresponding to 60 degree rotation
[[ 0.5       -0.8660254]
 [ 0.8660254  0.5      ]]
Matrix corresponding to -90 degree rotation
[[ 0  1]
 [-1  0]]
Matrix corresponding to 60 degree rotation to the nth power
[[ 1.00000000e+00  1.92694821e-15]
 [-1.99840144e-15  1.00000000e+00]]
Matrix corresponding to -90 degree rotation to the nth power
[[1 0]
 [0 1]]


# MANIPULATING VECTORS - WHY TO VECTORIZE?

In [21]:
# Compare different methods for computing dot products 
# of two vectors of size 10^6.

size_v = 1000000
v=np.linspace(0,1,size_v)
v1 = np.sin(v)
v2 = np.cos(v)
# You can measure elapsed time with this.
from timeit import default_timer as timer

# Try the proposed built-in vectorized procedure first.
start = timer()
v3 = v1@v2
end = timer()
print('Time it takes using the @ numpy operator')
print(end - start) # Time in seconds, e.g. 5.38091952400282
print('Actual result:')
print(v3)

# Second, apply a standard loop in Python.
start = timer()
v3 = 0
for j in range(size_v):
   v3 = v3 + v1[j]*v2[j]
end = timer()
print('Time it takes using for loop')
print(end - start) # Time in seconds, e.g. 5.38091952400282
print('Checking the result matches the previous one')
print(v3)

# Third, apply a fancy Python-procedure.
start = timer()
v3 = 0
for j in range(size_v):
    v3 += v1[j]*v2[j]
end = timer()
print('Time it takes using for loop with a different way of updating v')
print(end - start) # Time in seconds, e.g. 5.38091952400282
print('Checking the result matches the previous one')
print(v3)

Time it takes using the @ numpy operator
0.003898091003065929
Actual result:
354036.5824243151
Time it takes using for loop
0.5599387210095301
Checking the result matches the previous one
354036.58242431644
Time it takes using for loop with a different way of updating v
0.5339634169940837
Checking the result matches the previous one
354036.58242431644
