In [36]:
# we need it in all codes
import numpy as np 
import math

# we also need this one
from numpy.linalg import matrix_power

# see functions here
# https://numpy.org/doc/stable/reference/generated/numpy.exp.html
# https://numpy.org/doc/stable/reference/routines.array-manipulation.html
#

# basic vector and matrix operations
# general principle: we do not have to write functions for everything
# moreover, built-in vectorized operations are rather fast


#  MATRIX REPRESENTATIONS FOR LINEAR MAPPINGS

In [37]:
#create the matrix of the linear map that flips first and and 
#last coordinates in the three-dimensional 
#Euclidean space 
#Recall:  np.array ( [ [1st row ],  [2nd row ], ..., [nth row] ] )

#Goal, build A column by colum.

# First column

A =np.array( [ [0], [0], [1] ] )

print("A at start, just a column vector")
print(A)


print("shape of A:")


#np.hstack will add elements to each array horizontally
#to join arrays horizontally, they must have the same number of rows

print("Adding a new column with hstack")


print(A)


print("Adding a new column with hstack")


print(A)
#What is the 200th power of this matrix? use matrix_power(A,power)
print("Matrix power:")


# check this using a random vector
w = np.random.rand(3)

#Compare A@w  - (you flippling the coordinates of w by yourself)
print("checking if this actually flips vector coordinates, this outcome should be (0,0,0):")





A at start, just a column vector
[[0]
 [0]
 [1]]
shape of A:
Adding a new column with hstack
[[0]
 [0]
 [1]]
Adding a new column with hstack
[[0]
 [0]
 [1]]
Matrix power:
checking if this actually flips vector coordinates, this outcome should be (0,0,0):


In [38]:
#create the matrix of the linear map that flips first and and last coordinates in the 60-dimensional 
#Euclidean space. Hint, create an identity matrix of size nxn using np.eye(n).



In [39]:
#Create the matrix of the linear maps that multiplies the first 
#corrdinate with two, 
#the second one with three,
#  and the third coordinate will be 
#the sum of the first and second coordinates.

#Hint: Think of A transforming the basis functions 
# e_1 = (1, 0, 0), e_2 = (0,1,0), e_3 = (0,0,1)



print("what is the inverse of this matrix?")

#we can also see it by looking at the number of independent columns

what is the inverse of this matrix?


In [40]:
# Create the matrix corresponding to the rotation with 60 degrees and -90 degrees.
# Compute the 60th power of them
# Can you see this without any computation?

#60 degree rotation:

print("Matrix corresponding to 60 degree rotation")

# -90 degree rotation:
print("Matrix corresponding to -90 degree rotation")

# What happens if we use our rotation matrix 60 times?

print("Matrix corresponding to 60 degree rotation to the nth power")

# Roundoff errors may emerge.
print("Matrix corresponding to -90 degree rotation to the nth power")

# Take also the inverse of this matrix

# What is the image of the vector [1,2]?

# Which vector is mapped into [4,-2]?


Matrix corresponding to 60 degree rotation
Matrix corresponding to -90 degree rotation
Matrix corresponding to 60 degree rotation to the nth power
Matrix corresponding to -90 degree rotation to the nth power


# MANIPULATING VECTORS - WHY TO VECTORIZE?

In [41]:
# Compare different methods for computing dot products 
# of two vectors of size 10^6.

size_v = 1000000
v=np.linspace(0,1,size_v)

v1 = np.sin(v)
v2 = np.cos(v)
# You can measure elapsed time with this.
# At the beginning of the process you write e.g. start = timer(), and at the end e.g. end =timer()
# Then the total measured time will be end-start.
from timeit import default_timer as timer

# Try the proposed built-in vectorized procedure first (That is the @ operator).

print('Time it takes using the @ numpy operator')

print('Actual result:')

# Second, apply a standard loop in Python.


print('Time it takes using for loop')

print('Checking the result matches the previous one')



Time it takes using the @ numpy operator
Actual result:
Time it takes using for loop
Checking the result matches the previous one
