In [2]:
# We need it in all codes
import numpy as np 
import math

# See functions here
# https://numpy.org/doc/stable/reference/generated/numpy.exp.html
# https://numpy.org/doc/stable/reference/routines.array-manipulation.html

# METRICS

In [3]:
# Calculate Hamming distance of zero-one vectors.
# Compare two vectors of the same length containing only 0-1 digits.
# This is the ratio of the different sites.
#return sum(abs(e1 - e2) for e1, e2 in zip(a, b)) / len(a) 
#Remember we can see whats inside zip objects using list(zip(a,b))
#Because zip objects are iterators, once we use it it vanishes.
 
# define data
row1 = np.array([0, 0, 0, 0, 1])
row2 = np.array([1, 0, 0, 1, 0])

# calculate distance. We know that if row1[i] - row2 [i] are the same, then this sum is 0, otherwise is 1 or -1.
#Then we can calculate their Hamming distance by checking how many zeros this difference has:
dist = np.count_nonzero(row1 - row2)
print(dist)


# define data
row1 = np.array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
row2 = np.array([0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# calculate distance
dist = np.count_nonzero(row1 - row2)
print(dist)

# Ooh, these are quite similar, unlike the previous ones. However, 
# their distance are the same. 
# Therefore compute the RATIO of the different elements.

# define data
row1 = np.array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
row2 = np.array([0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# calculate distance
dist = np.count_nonzero(row1 - row2)/len(row1)
print(dist)


3
3
0.1875


In [4]:
# Try simlilar for the sum of the absolute value of the differences.
# We call it Manhattan distance or 1-distance.

# define data
row1 = np.array([-2, 0, 3, 4, 1])
row2 = np.array([2, 4, 0, 1, -1])

# calculate distance
dist = np.sum(abs(row1 - row2))
print(dist)
print(f"we can also use np.linalg.norm: {np.linalg.norm(row1-row2,1)}")
# Take again rather their average.

# define data
row1 = np.array([-2, 0, 3, 4, 1, 0])
row2 = np.array([2, 4, 0, 1, -1, 2])

# calculate this distance
dist = np.sum(abs(row1 - row2))/len(row1)
print(dist)




16
we can also use np.linalg.norm: 16.0
3.0


In [5]:
# Try similarly for the sum of the square of the differences.

# define data
row1 = np.array([-2, 0, 3, 4, 1])
row2 = np.array([2, 4, 0, 1, -1])

# calculate distance
dist = np.sum((row1 - row2)**2)
print(dist)

# Take again rather their average.

# define data
row1 = np.array([-2, 0, 3, 4, 1, 0])
row2 = np.array([2, 4, 0, 1, -1, 2])

# calculate this  "distance"
dist = np.sum((row1 - row2)**2)/len(row1)
print(dist)

# Be careful: this is not a distance (metrics)
# Take the square root.

dist = math.sqrt(np.sum((row1 - row2)**2)/len(row1))
print(dist)


54
9.666666666666666
3.1091263510296048


# WHICH ONE IS THE MIDPOINT?

In [6]:
# We have collected ten vectors in the rows of a matrix of size 10 x 10.
M = np.array([[2, 4, 7, 0, 1, 3, 4, 7, 3, 2],[3, 6, 6, 1, 0, 4, 6, 5, 3, 0],[3, 4, 7, 1, 2, 6, 4, 5, 2, 0],[2, 4, 6, 0, 0, 2, 3, 7, 2, 3],[1, 6, 8, -1, 1, 3, 4, 6, 2, 2],[1, 4, 6, 0, 0, 2, 3, 5, 3, 2],[3, 4, 8, -1, 1, 5, 6, 7, 3, 0],[1, 6, 7, 0, 0, 2, 4, 7, 3, 0],[2, 5, 7, 0, 1, 3, 4, 6, 2, 1],[3, 4, 7, -1, 1, 2, 3, 5, 3, 1]])
print(f' We will work with a matrix of size {M.shape}, each row represents a point in R^10')
# These should be included into a circle such that one of these points is
# the midpoint. Which one?

# We compute all of the distances first.

M_dist = np.zeros((10,10))
#
for j in range(0,10):
    for k in range(0,10):
        M_dist[j,k] = sum(abs(M[j,:] - M[k,:]))

x = np.amax(M_dist, 1)
print(x)
#Remember, d(xi, xj) = d(xj,xi ) !
M_dist = np.zeros((10,10))
for j in range(10):
    row_1 = M[j,:]
    row_2 = M[j+1:, :]
    M_dist [j,j+1:] = np.sum(abs(row_1-row_2), axis =1)
M_dist = M_dist + M_dist.T
# We take the maximum in all rows.   
x = np.amax(M_dist, 1)
print(x)

# Where this one is minimal, this will be the index we are looking for.
 
# This is the minimal value.    
print(min(x))

# This is the corresponding index.

np.argmin(x) +1


 We will work with a matrix of size (10, 10), each row represents a point in R^10
[13. 15. 15. 15. 14. 16. 16. 14. 11. 12.]
[13. 15. 15. 15. 14. 16. 16. 14. 11. 12.]
11.0


np.int64(9)

# GENETIC DISTANCE

In [7]:
# Take two toy genetic codes:
# [[A, A], [A, B], [A, A], [A, B, B], [A, B, B], [A, A, B], [A, A], [A, A, A], [C, C, B, A]]

# [[A, A], [B, B], [A, B], [A, A, B], [A, B, B], [A, A, B], [B, B], [A, A, C], [C, C, B, A]]


# We will manually transform and code them. [ how many As, How many Bs, How many Cs] :

S1 = np.array([[2, 0, 0], [1, 1, 0], [2, 0, 0], [1, 2, 0], [1, 2, 0], [2, 1, 0], [2, 0, 0], [3, 0, 0], [1, 1, 2]])

S2 = np.array([[2, 0, 0], [0, 2, 0], [1, 1, 0], [2, 1, 0], [1, 2, 0], [2, 1, 0], [0, 2, 0], [2, 0, 1], [1, 1, 2]])

# Compute the interior sums:
L = np.shape(S1)[0] #Gives us how many "chromosomes" or components  we have
s_mixed = np.zeros(np.shape(S1)[0]) #we will store the dot product of S1 and S2 
print(s_mixed)
#Computing dot product: 
for j in range(0,L):
    s_mixed[j] = S1[j,:]@S2[j,:] #this already measures similarity between two codes at component j.

#vectorization of the previous step! only need the diagonal since we dont need all possible comparisons of the components:
s_mixed_another_way = np.diag(S1@np.transpose(S2))  
#Checking they are actually the same:
print(s_mixed)
print(s_mixed_another_way)
#Ok, then we use this method to compute ||S1||^2 ||S2||^2 instead
s_1 = np.diag(S1@np.transpose(S1))
s_2 = np.diag(S2@np.transpose(S2))
#They store the dot product of each component:
print(s_1)
print(s_2)
genetic_distance = -np.log (sum(s_mixed)/math.sqrt(sum(s_1)*sum(s_2))) #the sum of all dot products / the sum of all norms squared
print(genetic_distance)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]
[4. 2. 2. 4. 5. 5. 0. 6. 6.]
[4 2 2 4 5 5 0 6 6]
[4 2 4 5 5 5 4 9 6]
[4 4 2 5 5 5 4 5 6]
0.21017401939993738
